spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wsmhz-shop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: redis
  application:
    name: front-order
server:
  port: 8093
  session:
    timeout: 3600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.wsmhz.order.common.data.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.wsmhz.common.business.mapper
  identity: MYSQL
#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
