spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      label: dev
      enabled: true
      server:
        git:
          uri: https://github.com/wsmhz/wsmhz-config-repository.git
          username: ${GIT_USER:787740644@qq.com}
          password: ${GIT_PASS:123456}
        encrypt:
          enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8081/eureka}
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
# 管理端点
#security:
#  basic:
#    enabled: false
management:
  endpoint:
    shutdown:
      # 开启 Shutdown 端点
      enabled: true
  endpoints:
    web:
      exposure:
        # 开启所有端点
        include:
          - '*'
encrypt:
  key: paascloud-key-store
#encrypt:
#  key: wsmhzAlias
